# Permalinks
permalink: pretty

# Setup
host: localhost
title: Andrew Hong
url: http://ahong080.github.io

author:
    name: Andrew Hong
    url: http://ahong080.github.io
    email: 

avatar: ASH.jpg
future: true
permalink: "/:title/"

pages_list:
    Profile: '/profile'
    Publications: '/publications'

markdown: kramdown

plugins:
    - jekyll-seo-tag

github: [metadata]
